### ISSUE TITLE
Blocked by OpenAI

### ISSUE THREAD

**Issue by aleung** [janlay/openai-cloudflare#2]
似乎是从今天起，这种cloudflare上的API proxy也被OpenAI block了。我尝试了一下，不送原始请求的header，依然不行。CF会自动添加 "cf-ipcountry": "CN" 这个 header。

网上找到有人遇到同样问题：
https://community.cloudflare.com/t/use-cloudflare-worker-to-reverse-proxy-openai-but-blocked/581714

**Comment by janlay** [comment]
谢谢反馈。你有试过主动添加 `cf-ipcountry: US` 这样的 header 吗？

**Comment by janlay** [comment]
I confirm that explicitly setting `CF-IPCountry: US` would be overwritten by Cloudflare. Finally this project comes to the end.

**Comment by fengwei18** [comment]
> I confirm that explicitly setting `CF-IPCountry: US` would be overwrite. Finally it comes to the end.

添加了还是不行，你本地ip确认是cn的吗？

**Comment by janlay** [comment]
> > I confirm that explicitly setting `CF-IPCountry: US` would be overwrite. Finally it comes to the end.
> 
> 添加了还是不行，你本地ip确认是cn的吗？

 嗯，添加了也无效，会被覆盖。我用本地直连测试是这样的。这个问题暂时无解了。

**Comment by Subdue0** [comment]
凉了凉了，昨天才用上，今天就没了。

**Comment by nivalxer** [comment]
看起来是cf目前会透传请求者IP所属地区，然后触发了openai的风控。小伙伴试了一下，在前面再套一个cdn可以解决，例如aws的cdn到cf的worker域名就行（必须得非CN地区的CDN节点）。

**Comment by jackie099** [comment]
> 看起来是cf目前会透传请求者IP所属地区，然后触发了openai的风控。小伙伴试了一下，在前面再套一个cdn可以解决，例如aws的cdn到cf的worker域名就行（必须得非CN地区的CDN节点）。

记得转发parameters和关闭cache

**Comment by aleung** [comment]
在后面用 Cloudflare AI Gateway 将 API 再代理一层就可以了。参考这个：https://github.com/flyisland/cf-openai-proxy/pull/1

**Comment by yushiro** [comment]
> 在后面用 Cloudflare AI Gateway 将 API 再代理一层就可以了。参考这个：https://github.com/flyisland/cf-openai-proxy/pull/1

感谢，套壳gateway成功访问api了，又复活了。

**Comment by janlay** [comment]
```
 ~/Desktop % curl -fsSL cloudflare.com/cdn-cgi/trace | grep loc=
loc=CN
 ~/Desktop % echo $OPENAI_API_ENDPOINT
https://***.janlay.net
 ~/Desktop % openai hello
Hello! How can I assist you today?
```
测试确认已解封
